### ISSUE TITLE
Parameterize date

### ISSUE THREAD

**Issue by rossabaker** [rossabaker/abolish-ice-graphiti#1]
dates.txt is based on June 13, 2020.  Instead of having a fixed data file, the script should calculate the dates on the fly.

**Comment by BenBE** [comment]
See #8 for a script to regenerate the `dates.txt` file.

**Comment by BenBE** [comment]
Any objections on closing this issue as there's tooling available to work with dates dynamically?

**Comment by rossabaker** [comment]
Nope, thanks for noticing.
