### ISSUE TITLE
Support BSD `date` command (and OS X)

### ISSUE THREAD

**Issue by wolfwood** [rossabaker/abolish-ice-graphiti#16]
abstract out calls to the date command into wrapper functions that can provide platform-specific behavior.

place platform check and functions in a script that can be `source`'d by `raster.sh` and `paint.sh`.

@lindsaylevine has discovered that the current approach doesn't work on OS X because GNU `date` and BSD `date` are different. reported in #8

**Comment by rossabaker** [comment]
I don't have access to test this, but it looks like a solution is emerging on #8. Would be happy to accept a PR on this.

**Comment by wolfwood** [comment]
yeah, just made this as a placeholder til I have a commit for a PR
