### ISSUE TITLE
Parameterize commit count

### ISSUE THREAD

**Issue by rossabaker** [rossabaker/abolish-ice-graphiti#2]
`$I` should be a command line option to trade speed vs. clarity, as described in the README.

**Comment by rossabaker** [comment]
It's not so much a speed issue anymore after #3, but still a nice idea.

**Comment by BenBE** [comment]
Isn't there a fourth column in the `dates.txt` anyway; so you'd just need to pull that value and (if not a positive number) fall back to some default:

```bash
I=${PARAMS[3]}
[ "$I" -gt 0 ] 2>/dev/null || I=180
```

You might need to update `dates.txt` to include something else than `4` in that column though. Also you might use some argument like `${1:-${PARAMS[3]}}` to get that initial value if none is given as first argument to the script.

**Comment by wolfwood** [comment]
https://glitch.com/~github-contribution-graph-art-generator has a javascript snippet to run in a web console while viewing your profile, to get max commits. maybe there is a way to automate that?

**Comment by BenBE** [comment]
You can get the list with the number of contributions like this:

```bash
user="$1"
if [ -z "${user}" ]; then
  contribs=$(curl -s "https://github.com/${user}"|tr '<> ' "\n"|grep data-count|tr '="' "\n"|grep -v data-count|grep -v '^$')
  max=0
  for i in ${contribs}
  do
    [ "${i}" -gt "${max}" ] 2>/dev/null && max="${i}"
  done
else
  max=42
fi
```

You get the idea …
