### ISSUE TITLE
Shorten by use of mkdir -p and pushd/popd

### ISSUE THREAD

**Issue by BenBE** [rossabaker/abolish-ice-graphiti#5]
The script may be shortened by using `mkdir -p "$Y/$M/$D"` instead of that cascade of nested `if` statements. Also traversing into that directory can be simplified when using `pushd "$Y/$M/$D"`/`popd` …

**Comment by BenBE** [comment]
You don't even need to eheck `[ ! -d "$Y/$M/$D" ]` as `mkdir -p` is a no-op if the target already exists.

**Comment by rossabaker** [comment]
Ah, true.  Also eliminated entirely by #6.
