### ISSUE TITLE
Abuse empty commits to save on IO

### ISSUE THREAD

**Issue by BenBE** [rossabaker/abolish-ice-graphiti#6]
Git allows for empty commits using `git commit --allow-empty` which makes all those extra directories unnecessary as you can just create a long series of (empty) commits with just your message as the commit content. Safes on both I/O when creating all those commits and also when pushing things (one object per commit instead of up to 5) …

**Comment by rossabaker** [comment]
Thanks. I just generated the initial script from the linked tool, but these were all good ideas.
